export const FETCH_WEATHER_FORECAST_END = "FETCH_WEATHER_FORECAST_END";
export const FETCH_WEATHER_FORECAST_START = "FETCH_WEATHER_FORECAST_START";

export const SET_WEATHER_FORECAST = "SET_WEATHER_FORECAST";
export const HISTORY_ADD = "HISTORY_ADD";
